"use client";
import { create } from "zustand";

export const useStore = create((set) => ({

    fashionProducts : [
  {
    id: 1,
    name: "Classic White T-Shirt",
    description: "Soft cotton crew-neck tee for everyday comfort.",
    price: 15.99,
    image: "https://i.pinimg.com/564x/c1/1d/16/c11d164de692594acf53c9a855093139.jpg",
    rating: 4.6,
    reviews: 235,
    inStock: true,
  },
  {
    id: 2,
    name: "Denim Jacket",
    description: "Vintage-style blue denim jacket with button closure.",
    price: 49.99,
    image: "https://hangten.com.pk/cdn/shop/files/denim-jacket-1.jpg?v=1734169858",
    rating: 4.8,
    reviews: 190,
    inStock: true,
  },
  {
    id: 3,
    name: "Black Slim Jeans",
    description: "Stretchable slim-fit black jeans for all-day wear.",
    price: 39.99,
    image: "https://sulfitclothing.co.uk/cdn/shop/files/SUL06871_94d2ee13-8f0c-46c5-8c8c-373872a9730f.jpg?v=1740255292",
    rating: 4.5,
    reviews: 320,
    inStock: true,
  },
  {
    id: 4,
    name: "Leather Handbag",
    description: "Genuine leather handbag with gold-tone hardware.",
    price: 79.99,
    image: "https://leatherskinshop.com/cdn/shop/products/product-image-496487611_1600x.jpg?v=1558902203",
    rating: 4.7,
    reviews: 150,
    inStock: true,
  },
  {
    id: 5,
    name: "Casual Sneakers",
    description: "Lightweight and stylish sneakers for everyday use.",
    price: 54.99,
    image: "https://1ststep.pk/cdn/shop/files/4_db5075ea-f798-4532-9bcb-feca73015c0a.webp?v=1743779025",
    rating: 4.4,
    reviews: 410,
    inStock: true,
  },
  {
    id: 6,
    name: "Men's Hoodie",
    description: "Soft fleece hoodie with front pocket and adjustable hood.",
    price: 34.99,
    image: "https://teetall.pk/cdn/shop/products/00123c8df31fed73e730fa4346446d77.webp?v=1695122271&width=533",
    rating: 4.3,
    reviews: 280,
    inStock: false,
  },
  {
    id: 7,
    name: "Silk Scarf",
    description: "Elegant silk scarf with floral pattern.",
    price: 24.99,
    image: "https://static-01.daraz.pk/p/768eb5dd140a3605e16ad2c29ce116f1.jpg",
    rating: 4.9,
    reviews: 95,
    inStock: true,
  },
  {
    id: 8,
    name: "Summer Dress",
    description: "Light and breezy floral print summer dress.",
    price: 45.99,
    image: "https://i.pinimg.com/736x/47/36/13/4736130ab1c11a31035868911e8ad8bf.jpg",
    rating: 4.6,
    reviews: 210,
    inStock: true,
  },
  {
    id: 9,
    name: "Woolen Sweater",
    description: "Warm and cozy wool sweater for cold days.",
    price: 59.99,
    image: "https://3.imimg.com/data3/XD/TD/MY-772681/wollen-sweater.jpg",
    rating: 4.5,
    reviews: 130,
    inStock: false,
  },
  {
    id: 10,
    name: "Sunglasses",
    description: "UV-protected polarized sunglasses with sleek design.",
    price: 29.99,
    image: "https://www.arzaan.pk/cdn/shop/products/re2_1024x1024.jpg?v=1684931902",
    rating: 4.8,
    reviews: 500,
    inStock: true,
  },
  {
    id: 11,
    name: "Leather Belt",
    description: "Adjustable brown leather belt with metal buckle.",
    price: 19.99,
    image: "https://pelikas.pk/cdn/shop/files/Heritage_Leather_belt.jpg?v=1717320746",
    rating: 4.7,
    reviews: 180,
    inStock: true,
  },
  {
    id: 12,
    name: "Formal Watch",
    description: "Elegant stainless steel watch with classic dial.",
    price: 89.99,
    image: "https://i.pinimg.com/736x/b3/1c/5c/b31c5c59cb6246e444d671e7576cd6ed.jpg",
    rating: 4.9,
    reviews: 270,
    inStock: true,
  },
],


 products : [
    {
        id: 1,
        name: "Wireless Headphones",
        description: "Noise-cancelling over-ear Bluetooth headphones with long battery life.",
        price: 99.99,
        category: "Electronics",
        rating: 4.6,
        reviews: 128,
        image: "https://havitstore.pk/cdn/shop/files/H2590.1596_1.png?v=1719232522",
        inStock: true,
    },
    {
        id: 2,
        name: "Smart Watch",
        description: "Waterproof smartwatch with fitness tracking and heart rate monitor.",
        price: 149.99,
        category: "Wearables",
        rating: 4.3,
        reviews: 85,
        image: "https://saamaan.pk/cdn/shop/products/Comet-Infinity-Smartwatch.jpg?v=1671009969",
        inStock: true,
    },
    {
        id: 3,
        name: "Running Shoes",
        description: "Lightweight running shoes designed for comfort and performance.",
        price: 79.99,
        category: "Fashion",
        rating: 4.8,
        reviews: 204,
        image: "https://static-01.daraz.pk/p/b6b9a2a1d1afe698dced6d2f50b1adb7.jpg",
        inStock: false,
    },
    {
        id: 4,
        name: "Gaming Mouse",
        description: "Ergonomic RGB gaming mouse with adjustable DPI and side buttons.",
        price: 49.99,
        category: "Accessories",
        rating: 4.7,
        reviews: 322,
        image: "https://d34mvw1if3ud0g.cloudfront.net/49776/Razer-Basilisk-V3_20250418-050555_full.jpeg",
        inStock: true,
    },
    {
        id: 5,
        name: "Bluetooth Speaker",
        description: "Portable waterproof speaker with powerful bass and long battery life.",
        price: 89.99,
        category: "Electronics",
        rating: 4.5,
        reviews: 210,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkzm330_QXVLpQJnT6jKW3ixSYYI9Vka9t6Q&s",
        inStock: true,
    },
    {
        id: 6,
        name: "Leather Wallet",
        description: "Premium leather wallet with multiple card slots and RFID protection.",
        price: 39.99,
        category: "Accessories",
        rating: 4.4,
        reviews: 97,
        image: "https://pelikas.pk/cdn/shop/files/DSC08321.jpg?v=1716807355",
        inStock: true,
    },
    {
        id: 7,
        name: "Laptop Backpack",
        description: "Durable and water-resistant backpack with USB charging port.",
        price: 59.99,
        category: "Fashion",
        rating: 4.6,
        reviews: 143,
        image: "https://dynsol.pk/cdn/shop/files/7_69278d90-2721-4db7-b499-a3cf31af5987.jpg?v=1698224104",
        inStock: true,
    },
    {
        id: 8,
        name: "Mechanical Keyboard",
        description: "RGB backlit mechanical keyboard with blue switches and metal frame.",
        price: 109.99,
        category: "Electronics",
        rating: 4.9,
        reviews: 276,
        image: "https://pakistanstore.pk/wp-content/uploads/2024/12/Xtrike-Me-GK-989-Gaming-Keyboard.jpg",
        inStock: true,
    },
    {
        id: 9,
        name: "Sunglasses",
        description: "Polarized UV400 protection sunglasses with stylish metal frame.",
        price: 24.99,
        category: "Fashion",
        rating: 4.2,
        reviews: 68,
        image: "https://m.media-amazon.com/images/I/21234RKjK2L._SY1000_.jpg",
        inStock: true,
    },
    {
        id: 10,
        name: "Wireless Charger",
        description: "Fast wireless charging pad compatible with iPhone and Android devices.",
        price: 29.99,
        category: "Electronics",
        rating: 4.3,
        reviews: 156,
        image: "https://appleman.pk/cdn/shop/files/acefast-e19-qi2-desktop-3in1-wireless-charging-holder-stand.jpg?v=1725087505&width=1445",
        inStock: false,
    },
],
    setProducts: (newProducts) => set({ products: newProducts }),

}));
