"use client";
import { create } from "zustand";

export const useStore = create((set) => ({

 products : [
    {
        id: 1,
        name: "Wireless Headphones",
        description: "Noise-cancelling over-ear Bluetooth headphones with long battery life.",
        price: 99.99,
        category: "Electronics",
        rating: 4.6,
        reviews: 128,
        image: "https://havitstore.pk/cdn/shop/files/H2590.1596_1.png?v=1719232522",
        inStock: true,
    },
    {
        id: 2,
        name: "Smart Watch",
        description: "Waterproof smartwatch with fitness tracking and heart rate monitor.",
        price: 149.99,
        category: "Wearables",
        rating: 4.3,
        reviews: 85,
        image: "https://saamaan.pk/cdn/shop/products/Comet-Infinity-Smartwatch.jpg?v=1671009969",
        inStock: true,
    },
    {
        id: 3,
        name: "Running Shoes",
        description: "Lightweight running shoes designed for comfort and performance.",
        price: 79.99,
        category: "Fashion",
        rating: 4.8,
        reviews: 204,
        image: "https://static-01.daraz.pk/p/b6b9a2a1d1afe698dced6d2f50b1adb7.jpg",
        inStock: false,
    },
    {
        id: 4,
        name: "Gaming Mouse",
        description: "Ergonomic RGB gaming mouse with adjustable DPI and side buttons.",
        price: 49.99,
        category: "Accessories",
        rating: 4.7,
        reviews: 322,
        image: "https://d34mvw1if3ud0g.cloudfront.net/49776/Razer-Basilisk-V3_20250418-050555_full.jpeg",
        inStock: true,
    },
    {
        id: 5,
        name: "Bluetooth Speaker",
        description: "Portable waterproof speaker with powerful bass and long battery life.",
        price: 89.99,
        category: "Electronics",
        rating: 4.5,
        reviews: 210,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkzm330_QXVLpQJnT6jKW3ixSYYI9Vka9t6Q&s",
        inStock: true,
    },
    {
        id: 6,
        name: "Leather Wallet",
        description: "Premium leather wallet with multiple card slots and RFID protection.",
        price: 39.99,
        category: "Accessories",
        rating: 4.4,
        reviews: 97,
        image: "https://pelikas.pk/cdn/shop/files/DSC08321.jpg?v=1716807355",
        inStock: true,
    },
    {
        id: 7,
        name: "Laptop Backpack",
        description: "Durable and water-resistant backpack with USB charging port.",
        price: 59.99,
        category: "Fashion",
        rating: 4.6,
        reviews: 143,
        image: "https://dynsol.pk/cdn/shop/files/7_69278d90-2721-4db7-b499-a3cf31af5987.jpg?v=1698224104",
        inStock: true,
    },
    {
        id: 8,
        name: "Mechanical Keyboard",
        description: "RGB backlit mechanical keyboard with blue switches and metal frame.",
        price: 109.99,
        category: "Electronics",
        rating: 4.9,
        reviews: 276,
        image: "https://pakistanstore.pk/wp-content/uploads/2024/12/Xtrike-Me-GK-989-Gaming-Keyboard.jpg",
        inStock: true,
    },
    {
        id: 9,
        name: "Sunglasses",
        description: "Polarized UV400 protection sunglasses with stylish metal frame.",
        price: 24.99,
        category: "Fashion",
        rating: 4.2,
        reviews: 68,
        image: "https://m.media-amazon.com/images/I/21234RKjK2L._SY1000_.jpg",
        inStock: true,
    },
    {
        id: 10,
        name: "Wireless Charger",
        description: "Fast wireless charging pad compatible with iPhone and Android devices.",
        price: 29.99,
        category: "Electronics",
        rating: 4.3,
        reviews: 156,
        image: "https://appleman.pk/cdn/shop/files/acefast-e19-qi2-desktop-3in1-wireless-charging-holder-stand.jpg?v=1725087505&width=1445",
        inStock: false,
    },
],
    setProducts: (newProducts) => set({ products: newProducts }),

}));
